# Generated by Django 4.0.1 on 2022-01-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('hero_points', models.IntegerField()),
                ('strength', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('hp', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('lvl', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('strength', models.IntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('hp', models.IntegerField()),
                ('xp_if_win', models.IntegerField()),
                ('lvl', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('has_quest', models.BooleanField()),
            ],
        ),
    ]
