# Generated by Django 4.0.1 on 2022-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='xp_if_completed',
            field=models.IntegerField(default=0),
        ),
    ]
