# Generated by Django 4.0.1 on 2022-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_npc_xp_if_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='position_x',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='position_y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
